import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LoginButton from "@/components/auth/LoginButton";
import { auth } from "@/lib/auth";
import SessionProvider from "@/components/common/SessionProvider";
import NavBar from "@/components/landing/NavBar";

const inter = Inter({ subsets: ["latin"] });

const BASE_PATH = "/api/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <SessionProvider basePath={BASE_PATH} session={session}>
        <body className={inter.className}>
          {/* <LoginButton /> */}
          <NavBar />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
